name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install and build frontend
        run: |
          cd frontend
          npm ci
          npm run build
          cd ..

      - name: Move frontend build to Laravel public
        run: |
          mv frontend/dist/* api-backend/public/

      - name: Setup PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2.6'

      - name: Install Laravel dependencies
        run: |
          cd api-backend
          composer update
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          cd ..

      - name: deploy to server
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}